[metadata]
name=pyrcore
version=1.0.0
author=Ricardo Werner Rivas
author_email=ricardowernerrivas@gmail.com
description=Creates an R core for Python
long_description=file:README.md
long_description_content_type=text/markdown
license=MIT
license_files=LICENSE
url=https://github.com/Ricardo-Werner-Rivas/pyrcore/tree/PyPI
project_urls=
    Bug Tracker=https://github.com/Ricardo-Werner-Rivas/pyrcore/issues
    Repository=https://github.com/Ricardo-Werner-Rivas/pyrcore
classifiers=
    Programming Language :: Python
    Operating System :: Microsoft :: Windows

[options]
packages=find:
install_requires=numpy

[options.extras_require]
df=pandas